version: '3.3'

services:
  backend:
    image: registry.cn-hangzhou.aliyuncs.com/yusiwen12138/gismap-backend:1.0.0
    container_name: gismap-backend
    expose:
      - "8088"
    networks:
      - app-network
  frontend:
    image: registry.cn-hangzhou.aliyuncs.com/yusiwen12138/gismap-frontend:1.0.0
    container_name: gismap-frontend
    ports:
      - "9090:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
