server:
  port: 8088
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
logging:
  level:
    root: info